<a href="https://colab.research.google.com/github/CarloRomer0/TareitaEjercicios_Numpy/blob/main/TareaNumpy_Jomwork_CarloRomero.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Tarea de Numpy**

Este notebook es el de los ejercicios >:)

In [ ]:
!pip install numpy
import numpy as np

# Probando si si jala el numpy
my_arreglow = np.array([1, 2, 3, 4, 5])

print(my_arreglow)
print(np.mean(my_arreglow))


[1 2 3 4 5]
3.0


## Ejercicios de refuerzo

### **Ejercicio 1 - Crear un array de ceros:**
Crea un array de tamaño (3, 4) lleno de ceros.

In [ ]:
# Solución (:
import numpy as np

arrayCeros = np.zeros((3,4))
print(arrayCeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### **Ejercicio 2-  Suma de elementos:**
   Dado el array [1, 2, 3, 4, 5], calcula la suma de todos sus elementos usando NumPy.

In [ ]:
# Solucion :)
import numpy as np

arrayNum = np.array([1,2,3,4,5])
suma = np.sum(arrayNum)
print(suma)

15


### **Ejercicio 3 - Encontrar el máximo y mínimo:**
Dado el array [10, 20, 30, 40, 50], encuentra el valor máximo y mínimo.

In [ ]:
array = np.array([10, 20, 30, 40, 50])

# Solución:)
max=np.max(array)
min=np.min(array)

print("Maximo", max)
print("Minimo", min)

Maximo 50
Minimo 10


### **Ejercicio 4 - Encontrar el máximo y mínimo:**
 Dado el array [10, 20, 30, 40, 50], encuentra el valor máximo y mínimo.


In [ ]:
# Solución:)
import numpy as np

arrayEncontrar= np.array([10,20,30,40,50])

max=np.max(arrayEncontrar)
min=np.min(arrayEncontrar)

print("Maximo", max)
print("Minimo", min)

Maximo 50
Minimo 10


### **Ejercicio 5 - Generar números aleatorios:**
  Genera un array de 5 números aleatorios entre 0 y 1.

In [ ]:
# Solución:)
import numpy as np

numAleatorios = np.random.rand(5)

print("Números aleatorios", numAleatorios)

Números aleatorios [0.79468598 0.66615936 0.93979306 0.08593196 0.9878822 ]


### **Ejercicio 6 - Promedio de un array:**
Dado el array [5, 10, 15, 20, 25], calcula su promedio usando NumPy.

In [ ]:
#Solucion:)
import numpy as np

arrayPromedio= np.array([5,10,15,20,25])
promedio=np.mean(arrayPromedio)

print("El promedio es", promedio)

El promedio es 15.0


### **Ejercicio 7 - Concatenar dos arrays**
Dados los arrays A = [1, 2, 3] y B = [4, 5, 6], concaténalos en un solo array.

In [ ]:
#Solucion:)
import numpy as np

A=np.array([1,2,3])
B=np.array([4,5,6])

unirArrays=np.concatenate((A,B))
print("Así esta el array unido", unirArrays)


Así esta el array unido [1 2 3 4 5 6]


### **Ejercicio 8 - Reshape de un Array**
Dado el array [1, 2, 3, 4, 5, 6], cámbialo a una matriz de 2x3.

In [ ]:
#Solución:)
import numpy as np

array=np.array([1,2,3,4,5,6])
matriz=array.reshape((2,3))

print("La matriz 2x3")
print(matriz)

La matriz 2x3
[[1 2 3]
 [4 5 6]]


### **Ejercicio 9 - Producto punto (dot product):**
Dados dos arrays A = [1, 2, 3] y B = [4, 5, 6], calcula su producto punto

In [ ]:
#Solución:)
import numpy as np

A=np.array([1,2,3])
B=np.array([4,5,6])

productoPunto=np.dot(A,B)

print("El producto punto es", productoPunto)

El producto punto es 32


### **Ejercicio 10 - Reorganizar un array:**
Dado el array [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], conviértelo en una matriz (2, 5).

In [ ]:
#Solución:)
import numpy as np

array=np.array([1,2,3,4,5,6,7,8,9,10])

matrizReorganizar=array.reshape((2,5))

print("Convertido a matriz 2x5")
print(matrizReorganizar)

Convertido a matriz 2x5
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


### **Ejercicio extra - Encontrar el *k*-ésimo elemento más pequeño en un array**
Dado arr = np.array([9, 3, 6, 2, 1, 7]), encuentra el 3er elemento más pequeño sin ordenar el array completo.

**Pista solución 1**: Se puede hacer con un método de Numpy

**Pista solución 2**: El código se hace más complicado, pero se puede resolver con ciclos iterativos.

In [19]:
#Solucion :o
import numpy as np
arr = np.array([9, 3, 6, 2, 1, 7])
posicion = 3

numMenor = np.partition(arr, posicion-1)
print("El 3er numero más pequeño es", numMenor)

El 3er numero más pequeño es [1 2 3 6 7 9]


## **Ejercicios aplicados**

### **Ejercicio: Cálculo de ROI (Retorno de Inversión)**
Dadas las inversiones ([1000, 1500, 2000]) y sus retornos ([1200, 1650, 1800]), calcula el ROI porcentual para cada caso.

*(Fórmula: ROI = (retorno - inversión) / inversión * 100)*

In [9]:
# Solucion del ROIROIROIROIORIORI
inversion= np.array([1000,1500,2000])
retorno= np.array([1200,1650,1800])

roi= ((retorno - inversion) / inversion * 100)

print("El calculo de ROI es:", roi)

El calculo de ROI es: [ 20.  10. -10.]


### **Ejercicio: Normalización de Datos**
Tienes un dataset de precios de productos (en USD): [250, 320, 150, 500, 210]. Normaliza los valores al rango [0, 1] para compararlos en una escala común.

**Formulita de la normalización**: (x - min) / (max - min): Para una escala valores entre 0 y 1.

In [11]:
import numpy as np

dataset= np.array([250,320,150,500,210])

minimo=np.min(dataset)
maximo=np.max(dataset)

normalizado= (dataset - minimo) / (maximo - minimo)

print("El valor normalizado es", normalizado)

El valor normalizado es [0.28571429 0.48571429 0.         1.         0.17142857]


### **Ejercicio: Filtrado de Datos**
En un array de ventas diarias ([1200, 0, 750, 2400, 0, 1800]), reemplaza los ceros (días sin ventas) por el promedio de los días con ventas.

In [13]:
import numpy as np

ventasDiarias= np.array([1200,0,750,2400,0,1800])

dias_Ventas=ventasDiarias[ventasDiarias !=0]

promedio = np.mean(dias_Ventas)

ventasDiarias[ventasDiarias == 0] = promedio

print("Los dias con ventas son", ventasDiarias)

Los dias con ventas son [1200 1537  750 2400 1537 1800]


### **Ejercicio - Análisis de Presión Arterial**
Tenemos un dataset de mediciones de presión arterial sistólica (mmHg) de 10 pacientes:
[120, 135, 140, 118, 150, 130, 160, 125, 142, 128].

Calculen:
- Media y desviación estándar.
- Identifiquen valores fuera del rango normal (90–140 mmHg).

In [14]:
import numpy as np

presionArterial= np.array([120,135,140,118,150,130,160,125,142,128])

media=np.mean(presionArterial)
desviacion=np.std(presionArterial)

print("La media es", media)
print("La desviación es", desviacion)

La media es 134.8
La desviación es 12.69488085804668


### **Ejercicio - Cálculo del PIB per Cápita**
Dados el PIB (en millones de USD) [500, 320, 700, 450] y la población (en millones) [10, 8, 12, 9] de 4 países, calculen el PIB per cápita y determinen el país con el mayor valor.

In [22]:
import numpy as np

PIB=np.array([500, 320, 700, 450])
poblacion= np.array([10, 8, 12, 9])

PIBperCapita= PIB/poblacion

mayorPIB=np.argmax(PIBperCapita)

print("El PIB per cápita es", PIBperCapita)
print("El pais con mayor PIB per capita es", mayorPIB )

El PIB per cápita es [50.         40.         58.33333333 50.        ]
El pais con mayor PIB per capita es 2


### **Ejercicio - Sistema de Drops (Probabilidades)**
En un videojuego RPG, los enemigos al ser vencidos, pueden dropear (soltar):
- 0 = Nada (50%).
- 1 = Poción (30%).
- 2 = Arma (15%).
- 3 = Artefacto (5%).

Simula 100 drops y cuenta cuántos artefactos se obtuvieron.

*Ejemplo de salida*:

```
Artifactos obtenidos: 3
```



In [35]:
import numpy as np

probabilidades = [0.5, 0.3, 0.15, 0.05]

dropeos = np.random.choice([0,1,2,3], size=100, p=probabilidades)

numArtefactos = np.count_nonzero(dropeos == 3)

print("Artefactos obtenidos:", numArtefactos)



Artefactos obtenidos: 3
